version: 2.1
orbs:
  #installs the required Orbs to execute the required commands in the build enviroment
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1 # to be able to use aws Cli and deploy FrontEnd files
  eb: circleci/aws-elastic-beanstalk@2.0.1 # to be able to deploy BackEnd to Elastic Beanstalk
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      # To configure the Building Enviroments
      - node/install
      - checkout
      - run:
          name: Front-End Install #Install Front-End Dependencies 
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install #Install Back-End Dependencies 
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - "./*"
      
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - checkout
      - node/install
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End deploy # Run Deployment Sceript to deply Front-End to S3
          command: |
            npm run frontend:deploy
      - run:
          name: Back-End preDeploy # Run Deployment Sceript to deply Back-End to EB
          command: |
            npm run backend:predeploy


workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main